# Generated by Django 3.1.3 on 2020-11-19 10:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_auto_20201119_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='user_read',
            field=models.ManyToManyField(related_name='read_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
